export enum EThemeColors {
  shark = 'var(--color-shark)',
  charade = 'var(--color-charade)',
  brightGray = 'var(--color-bright-gray)',
  cadetBlue = 'var(--color-cadet-blue)',
  shuttleGray = 'var(--color-shuttle-gray)',
  white = 'var(--color-white)',
  whiteRGB = 'var(--color-white-rgb)',
  kournikova = 'var(--color-kournikova)',
  kournikovaRGB = 'var(--color-kournikova-rgb)',
  dodgerBlue = 'var(--color-dodger-blue)',
  dodgerBlueRGB = 'var(--color-dodger-blue-rgb)',
  grannySmithApple = 'var(--color-granny-smith-apple)',
  grannySmithAppleRGB = 'var(--color-granny-smith-apple-rgb)',
  geraldine = 'var(--color-geraldine)',
  geraldineRGB = 'var(--color-geraldine-rgb)',
  heliotrope = 'var(--color-heliotrope)',
  heliotropeRGB = 'var(--color-heliotrope-rgb)',
}
